// <auto-generated />
using MediaOrganiser.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MediaOrganiser.Migrations
{
    [DbContext(typeof(MediaOrganiserContext))]
    [Migration("20190214152237_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MediaOrganiser.Models.MediaFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryID");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<string>("Description");

                    b.Property<int>("MediaTypeID");

                    b.Property<string>("Name");

                    b.Property<byte>("SizeMB");

                    b.Property<byte[]>("Thumbnail");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.ToTable("MediaFile");
                });
#pragma warning restore 612, 618
        }
    }
}
